BEGIN;

-- Generated from tabla.txt. Blank or invalid source values are imported as NULL.
-- Source records: 272

INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Jairo Omar Escoto', '100mg', NULL, '10.10.20.2', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Jairo Omar Escoto', '100mg', NULL, '10.10.20.3', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Edwin Alexander Lopez', '50mg', 599, '10.10.20.4', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Keyli Gualdina Barahona', '25mg', 549, '10.10.20.5', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Ever Josue Ramirez', '20mg', 499, '10.10.20.6', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Keylin Gisela Johnson', '30mg', 499, '10.10.20.7', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Wilfredo Alfaro Acosta', '20mg', 499, '10.10.20.8', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Walter Antonio Benedith', '20mg', 499, '10.10.20.9', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Wilmer Rene Varela', '20mg', 499, '10.10.20.10', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Francisco Eduardo Ayala', '20mg', 499, '10.10.20.11', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Lucas Antonio Garcia', '20mg', 549, '10.10.20.12', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Sarina Elizabeth Cilvas', '20mg', 499, '10.10.20.13', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Carmen Antonia Menocal', '20mg', 499, '10.10.20.14', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Hector Efrain Jimenez', '70mg', 749, '10.10.20.15', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Angel Donay Lopez', '20mg', 499, '10.10.20.16', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Victor Vangel Zepeda', '20mg', 499, '10.10.20.17', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Greysi Castro', '20mg', 499, '10.10.20.18', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Dania Hiracema Guillen', '20mg', 499, '10.10.20.19', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Lesly Patricia Mejia', '40mg', 549, '10.10.20.20', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Darwin Ramiro Gonzales', '20mg', 499, '10.10.20.21', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Senia Cristina Medina', '20mg', 499, '10.10.20.22', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Yanelyn Alexandra Vallecillo', '80mg', 749, '10.10.20.23', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Jose Maria Milla', '20mg', 499, '10.10.20.24', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Manuel Escobar Alcantara', '30mg', 499, '10.10.20.25', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Lorna Elizabeth Alvarez', '20mg', 499, '10.10.20.26', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Juan Jose Norales', '20mg', 499, '10.10.20.27', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Dayron Eberto Guillen', '50mg', 599, '10.10.20.28', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Marco Antonio Herrera', '30mg', NULL, '10.10.20.29', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Hilda Melendez Mejia', '30mg', 499, '10.10.20.30', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Carmen Nohemi Flores', '30mg', 499, '10.10.20.31', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Kerwin Vanessa Castro', '20mg', 499, '10.10.20.32', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Mario Roberto Ulloa', '50mg', 649, '10.10.20.33', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Neptali Jeremia Martinez', '20mg', 499, '10.10.20.34', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Delmi Ondina Medina', '40mg', 599, '10.10.20.35', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Linda Delians Padilla', '20mg', 499, '10.10.20.36', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Juana Orellana', '25mg', 549, '10.10.20.37', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Lasby Abigail Gutierrez', '40mg', 549, '10.10.20.38', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Suami Odan Lara', '20mg', 499, '10.10.20.39', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Kevin Solis', '30mg', 550, '10.10.20.40', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Ivania Yelisa Solis', '30mg', 549, '10.10.20.41', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Yessel Cruz', NULL, NULL, '10.10.20.42', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Blanca Azucena Hernandez', '20mg', 499, '10.10.20.43', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Ruth Nohemi Castillo', '35mg', 599, '10.10.20.44', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Alma Iris Delgado', '20mg', 499, '10.10.20.45', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Sandra Lemus', '20mg', 499, '10.10.20.46', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Wendy Chrino', '40mg', 600, '10.10.20.47', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Elvis Noe Perez', '20mg', 499, '10.10.20.48', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Sol Perdomo', '20mg', 499, '10.10.20.49', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Digna Esperanza Hernandez', '20mg', 499, '10.10.20.50', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Elder Odiel Torres', '50mg', 649, '10.10.20.51', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Vilma Esnelda Ocampo', '30mg', 499, '10.10.20.52', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Dania Patricia Martinez', '20mg', 499, '10.10.20.53', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Beatriz Castellano', '40mg', 600, '10.10.20.54', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Hector Fernando Lopez', '30mg', 550, '10.10.20.55', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Melvin Lemus', '45mg', 649, '10.10.20.56', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Luis Arturo Ascenso', '80mg', 600, '10.10.20.57', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Jose Alfredo Santos', '20mg', 499, '10.10.20.58', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Antonia Flores', '30mg', 499, '10.10.20.59', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Reyna Leticia Manchama', '35mg', 600, '10.10.20.60', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Roger Manuel Cerrato', '50mg', 599, '10.10.20.61', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Carlos Daneri Castellano', '30mg', 549, '10.10.20.62', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Yensi Yamileth Mejia', '35mg', 599, '10.10.20.63', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Simon Antonio Madrid', '30mg', 499, '10.10.20.64', NULL, 3);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Rigoberto Yillega', '30mg', 499, '10.10.20.65', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Josefa Vargas Menocal', '30mg', 499, '10.10.20.66', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Hector Rolando Mendez', '20mg', 499, '10.10.20.67', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Carmen Nohemi Flores', '30mg', 499, '10.10.20.68', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Orlin Joel Canan', '20mg', 499, '10.10.20.69', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Juan Santos Ortiz', '20mg', 499, '10.10.20.70', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Mary Stefani Ordoñez', '40mg', 549, '10.10.20.71', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Ruth America Aguilar', '55mg', 700, '10.10.20.72', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Antonio Javier Espinoza', '45mg', 649, '10.10.20.73', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Maria Reyna Nuñez', '20', 499, '10.10.20.74', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Danis Omar Martinez', '20', 499, '10.10.20.75', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Jaime Smith Jonhson', '20', 499, '10.10.20.76', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, NULL, NULL, NULL, '10.10.20.77', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Wilfredo Vallecillo', '20', 499, '10.10.20.78', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Luis Alfredo Delgado', '20', 499, '10.10.20.79', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Cirio Telemaco Lopez', '30', 499, '10.10.20.80', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Oscar Omar Osorio', '40', 629, '10.10.20.81', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'C.E.B. Elvira Tome', '50', NULL, '10.10.20.82', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Ingrid Graciela Serrano', '20', 499, '10.10.20.83', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Blanca Luz Lopez', '20', 499, '10.10.20.84', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Sandra Cardina Ramirez', '20', 499, '10.10.20.85', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Esmerita Santos Diaz', '20', 499, '10.10.20.86', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Alba Nubia Fugon', '35', 599, '10.10.20.87', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Kenia Yaneth Ordoñez', '80', 749, '10.10.20.88', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Mixi Dayana Sauceda', '20', 499, '10.10.20.89', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Oscar Alfredo Mejia', '30', 499, '10.10.20.90', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Yenifer Dayana Romero', '20', 499, '10.10.20.91', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Hector Efrain Jimenez', '70', 749, '10.10.20.92', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Jose Nelson Madrid', '20', 499, '10.10.20.93', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Oscar Geovani Izaguirre', '20', 499, '10.10.20.94', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Marco Aurelio Chirinos', '20', 499, '10.10.20.95', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Maria Mercedes Andino', '20', 499, '10.10.20.96', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Fanny Mayela Garcia', '30', 499, '10.10.20.97', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Karen Roxana Romero', '30', 499, '10.10.20.98', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Cristhian Humberto Argueta', '80', 749, '10.10.20.99', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Yeison Fernando Ocampo', '25', 549, '10.10.20.100', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Leyla Margoth Johnson', '20', 499, '10.10.20.101', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Tomas Vasquez', '20', 499, '10.10.20.102', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Carlos Joel Reyes', '20', 499, '10.10.20.103', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Nidia Mayela Guillen', '20', 499, '10.10.20.104', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Jose Orlando Flores', '40', 549, '10.10.20.105', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Alicia Yolani Escobar', '30', 499, '10.10.20.106', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Reyna Maribel Espinoza', '25', 549, '10.10.20.107', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Esteban Diaz', '30', 499, '10.10.20.108', NULL, 3);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Jose Saul Mejia', '20', 499, '10.10.20.109', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Sirey Williams', '30', 499, '10.10.20.110', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Marlon Yovani Marquina', '20', 499, '10.10.20.111', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Jose Federico Bueso', '25', 549, '10.10.20.112', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Eli Nacal Giron', '25', 549, '10.10.20.113', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Ronny Marcala Enamorado', '40', 549, '10.10.20.114', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Jairo Omar Escoto', '50', NULL, '10.10.20.115', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Francisca Meraz', '20', 499, '10.10.20.116', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Karla Suleyka Alvarez', '40', 549, '10.10.20.117', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Osmin Jonathan Rodriguez', '30', 499, '10.10.20.118', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Mariano Bonilla', '25', 549, '10.10.20.119', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Daniel Rodriguez Villalobo', '20', 499, '10.10.20.120', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Rigoberto Yillega', '20', 499, '10.10.20.121', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Digna Esperanza Bonilla', '20', 499, '10.10.20.122', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Daniel Rumaldo Norales', '35', 599, '10.10.20.123', NULL, 3);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Ana Lourdes Martinez', '80', 749, '10.10.20.124', NULL, 3);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Maria Olimpia Rivera', '30', 499, '10.10.20.125', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Hurbin Elizabeth Dueños', '40', 600, '10.10.20.126', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Merary Yamileth Cruz', '30', 549, '10.10.20.127', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Gabriel Omar Castillo', '50', 599, '10.10.20.128', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Digna Yamileth Ponce', '60', 649, '10.10.20.129', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Martha Isabel Lopez', '20', 499, '10.10.20.130', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Francisca Guzman', '20', 499, '10.10.20.131', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Lucas Hernandez Velasco', '20', 499, '10.10.20.132', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Elmer Misael Perez', '50', 649, '10.10.20.133', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Olvin Leonel Hernandez', '25', 549, '10.10.20.134', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Jose Santiago Guzman', '20', 499, '10.10.20.135', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Nolvia Isabel Palma', '40', 600, '10.10.20.136', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Dimas David Barahona', '45', 649, '10.10.20.137', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Campamento Elin', NULL, NULL, '10.10.20.138', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Evangelina Gonzales', '20', 499, '10.10.20.139', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Jose Rigoberto Amador', '20', 499, '10.10.20.140', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Jose Antonio Fuentes', '20', 499, '10.10.20.141', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Angela Candida Reyes', '20', 499, '10.10.20.142', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, NULL, NULL, NULL, '10.10.20.143', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Jose Esai Ferrera', '30', 549, '10.10.20.144', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Elmer Misael Perez', '20', 499, '10.10.20.145', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Danila Isabel Romero', '20', 450, '10.10.20.146', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Rony Williams', '30', 549, '10.10.20.147', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Dilcia Catalina Reyes', '20', 499, '10.10.20.148', NULL, 3);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Nancy Margoth Agurcia', '20', 499, '10.10.20.149', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Jose Raul Ruiz', '20', 499, '10.10.20.150', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Reyna Elizabeth Oseguera', '30', 549, '10.10.20.151', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Dixon Gabril Diaz', '25', 499, '10.10.20.152', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Sofia Cruz Gomez', '20', 499, '10.10.20.153', NULL, 3);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Daniel Alberto Flores', '30', 499, '10.10.20.154', NULL, 3);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Carlos David Salazar', '30', 499, '10.10.20.155', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Elias Pineda Bonilla', '30', 499, '10.10.20.156', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Jose Naun Joval', '20', 499, '10.10.20.157', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Paula Orellana', '30', 499, '10.10.20.158', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Jose Evelio Lopez', '50', 549, '10.10.20.159', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Jose David Pineda', '20', 499, '10.10.20.160', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Jose Antonio Santos', '40', 450, '10.10.20.161', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Yerlin Yaquelin Sandoval', '20', 499, '10.10.20.162', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Beesai Licona Giron', '45', 649, '10.10.20.163', NULL, 3);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Sabino Ramirez Garcia', '35', 599, '10.10.20.164', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Xiomara Lourdes Castillo', '25', 549, '10.10.20.165', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Byron Geovani Escobar', '30', 499, '10.10.20.166', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Sandra Yamileth Valdes', '25', 549, '10.10.20.167', NULL, 3);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Ada Yadira Cruz', '20', 499, '10.10.20.168', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Cinthia Fabiola Ocampo', '50', 600, '10.10.20.169', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Junior Marel Calix', '20', 499, '10.10.20.170', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Melkis Alberto Salgado', '20', 499, '10.10.20.171', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Maria Alba Luz Vasquez', '20', 499, '10.10.20.172', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Osma Oneyda Colindre', '20', 499, '10.10.20.173', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Olvan Edildo Cardona', '20', 499, '10.10.20.174', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Alex Said Hernandez', '30', 499, '10.10.20.175', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Mariana Leiva Portillo', '20', 499, '10.10.20.176', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Sonia Esmeralda Euceda', '40', 599, '10.10.20.177', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Luica Chacon Ochoa', '20', 499, '10.10.20.178', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Sara Esmerita Barahona', '20', 499, '10.10.20.179', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Elbira Kley Bolaños', '40', 599, '10.10.20.180', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Carmen Florinda Gutierrez', '30', 549, '10.10.20.181', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Aron Isaac Sandoval', '50', 599, '10.10.20.182', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Erlan Ariel Cartagena', '40', 549, '10.10.20.183', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Irma Manuela Ruiz', '30', 499, '10.10.20.184', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Nanci Olivia Carcamo', '60', 649, '10.10.20.185', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Jairo Efrain Galan', '30', 499, '10.10.20.186', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Jairo Efrain Galan', '30', 499, '10.10.20.187', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Janeth Araceli Elvir', '30', 499, '10.10.20.188', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Dania Lizeth Perez', '50', 599, '10.10.20.189', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Keylin Julissa Lopez', '30', 499, '10.10.20.190', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Jose Hernan Martinez', '30', 499, '10.10.20.191', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Erick Napoleon Lobo', '30', 499, '10.10.20.192', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Marlen Esperanza Escobar', '30', 499, '10.10.20.193', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Kevin Antonio Escobar', '40', 549, '10.10.20.194', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Bertha Lidia Mongoia', '30', 499, '10.10.20.195', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Rosa Carminda Espinoza', '30', 450, '10.10.20.196', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Ramona Adelina Valladares', '30', 499, '10.10.20.197', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Dilcia Nohemi Cornejo', '60', 649, '10.10.20.198', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Irma Esperanza Cardoza', '30', 499, '10.10.20.199', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Alexis Nicolas Moradel', '30', 499, '10.10.20.200', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Blanca Lidia Ramirez', '30', 499, '10.10.20.201', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Orlando Javier Redondo', '40', 549, '10.10.20.202', NULL, 3);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Maria Eugenia Tome', '30', 499, '10.10.20.203', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Marleni Lizeth Valle', '40', 549, '10.10.20.204', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Elkin Arial Valle', '30', 499, '10.10.20.205', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Rommel Hernan Ramirez', '100', 999, '10.10.20.206', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Obed Isai Herrera Garcia', '30', 499, '10.10.20.207', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Celia Yanira Chaves', '40', 549, '10.10.20.208', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Leticia Martinez Lopez', '40', 549, '10.10.20.209', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Juan Carlos Morazan', '30', 499, '10.10.20.210', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Napoleon Gutierrez', '30', 499, '10.10.20.211', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Efrain Rufino Galan', '30', 499, '10.10.20.212', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Roberto Ramon Escalante', '60', 649, '10.10.20.213', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Jaime Orlando Contrera', '30', 499, '10.10.20.214', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Nicolasa Rodriguez', '30', 499, '10.10.20.215', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Silvia Maritza Hernandez', '30', 499, '10.10.20.216', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Omar Alberto Sanchez', '50', 599, '10.10.20.217', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Maria Bautista Aguirre', '30', 499, '10.10.20.218', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Wilfredo Solorzano Mejia', '30', 499, '10.10.20.219', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Isis Paola Rosales', '40', 549, '10.10.20.220', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Douglas Dionicio Rodriguez', '30', 499, '10.10.20.221', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, NULL, NULL, NULL, '10.10.20.222', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Rosmary Elwin Dias', '30', 499, '10.10.20.223', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Ernesto Jouse Escobar', '40', 549, '10.10.20.224', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Kensi Yareli Hernandez', '30', 599, '10.10.20.225', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Zonia Danitza Perez', '30', 499, '10.10.20.226', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Henry Celin Castro', '50', 599, '10.10.20.227', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Gibran Fernando Lozano', '80', 749, '10.10.20.228', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Vanessa Castro', '30', 499, '10.10.20.229', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Heydi Lohani Ramirez', '50', 680, '10.10.20.230', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Allan Lenin Tome', '30', 499, '10.10.20.231', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Nanci Esmeralda Ruiz', '60', 650, '10.10.20.232', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Wendy Sarai Hernandez', '40', 549, '10.10.20.233', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Jorge Alberto Castro', '200', 1500, '10.10.20.234', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Ruth Nohemi Meraz', '50', 600, '10.10.20.235', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Marixa Yamileth Acosta', '40', 549, '10.10.20.236', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Carlos Elias Ramirez', '50', 600, '10.10.20.237', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Yadira Josselin Mejia', '30', 499, '10.10.20.238', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Osmin Jose Banegas', '40', 549, '10.10.20.239', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Jose Virgilio Ramirez', '30', 499, '10.10.20.240', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Mirta Leticia Solis', '30', 499, '10.10.20.241', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Armando Orellana', '30', 499, '10.10.20.242', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Mercedes Corrales', '30', 499, '10.10.20.243', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Fanny Mayela Garcia', '30', 499, '10.10.20.244', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, NULL, NULL, NULL, '10.10.20.245', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, NULL, NULL, NULL, '10.10.20.246', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Olbin Nahun Rodriguez', '40', 549, '10.10.20.247', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Darkin Noel Meza', '30', 499, '10.10.20.248', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Felicita Emelina Meraz', '30', 499, '10.10.20.249', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Tania Olivia Mistrick', '50', 599, '10.10.20.250', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Rosalba Gallardo', '40', 549, '10.10.20.251', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Jorge Luis Heredia', '80', 749, '10.10.20.252', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Rigoberto Hernandez', '30', 499, '10.10.20.253', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Jose Rolando Tabora', '40', 549, '10.10.20.254', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Wilmer Adonay Lemus', '30', 499, '10.10.21.2', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Mirian Julissa Solis', '60', 649, '10.10.21.3', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Yeni Yaqueline Cantarero', '30', 499, '10.10.21.4', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Seyli Carina Lemus', '50', 599, '10.10.21.5', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Stefany Nicol Herrera', '60', 649, '10.10.21.6', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Laura Ester Dubon', '30', 499, '10.10.21.7', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Candida Carolina Gutierrez', '50', 599, '10.10.21.8', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Nanci Nohemi Lopez', '40', 549, '10.10.21.9', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Sandra Lizzeth Hernandez', '50', 599, '10.10.21.10', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Blanca Rosa Reyes', '50', 599, '10.10.21.11', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Luisa Aguilar', '30', 499, '10.10.21.12', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Kenia Julissa Caceres', '30', 499, '10.10.21.13', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Allison Yojana Miranda', '40', 549, '10.10.21.14', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Tania Lourdes Rivera', '30', 499, '10.10.21.15', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Edil Osiris Maradiaga', '30', 499, '10.10.21.16', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Heydi Rosmari Rodriguez', '30', 499, '10.10.21.17', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Carlos Alfredo Caceres', '50', 599, '10.10.21.18', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Karla Stephany Perdomo', '30', 499, '10.10.21.19', NULL, NULL);
INSERT INTO clientes (fecha_conexion, abonado, plan, valor, ip, ultimo_mes_pagado, id_estado) VALUES (NULL, 'Cinthia Fabiany Midena', '60', 649, '10.10.21.20', NULL, NULL);

COMMIT;
