CREATE TABLE IF NOT EXISTS estados (
    id_estado INTEGER PRIMARY KEY,
    nombre VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS usuarios (
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario VARCHAR(80) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO estados (id_estado, nombre)
VALUES
    (1, 'Al dia'),
    (2, 'En mora'),
    (3, 'Cortado')
ON CONFLICT (id_estado) DO UPDATE
SET nombre = EXCLUDED.nombre;

CREATE TABLE IF NOT EXISTS clientes (
    id_cliente INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_conexion DATE NULL,
    abonado VARCHAR(150) NULL,
    plan VARCHAR(30) NULL,
    valor NUMERIC(10, 2) NULL,
    ip VARCHAR(45) NULL,
    ultimo_mes_pagado DATE NULL,
    id_estado INTEGER NULL,

    CONSTRAINT fk_cliente_estado
        FOREIGN KEY (id_estado)
        REFERENCES estados (id_estado)
);

CREATE UNIQUE INDEX IF NOT EXISTS clientes_ip_unique
    ON clientes (ip)
    WHERE ip IS NOT NULL;
