import bcrypt from 'bcryptjs'
import { Client } from 'pg'

const databaseUrl = process.env.DATABASE_URL
const username = process.env.ADMIN_USERNAME || 'Antonio'
const password = process.env.ADMIN_PASSWORD

if (!databaseUrl || !password) {
  console.error('Faltan DATABASE_URL o ADMIN_PASSWORD.')
  process.exit(1)
}

const client = new Client({
  connectionString: databaseUrl,
  ssl: { rejectUnauthorized: false },
})

try {
  await client.connect()
  await client.query(`
    CREATE TABLE IF NOT EXISTS usuarios (
      id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      usuario VARCHAR(80) NOT NULL UNIQUE,
      password_hash VARCHAR(255) NOT NULL,
      activo BOOLEAN NOT NULL DEFAULT TRUE,
      creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `)
  const passwordHash = await bcrypt.hash(password, 12)
  await client.query(
    `INSERT INTO usuarios (usuario, password_hash)
     VALUES ($1, $2)
     ON CONFLICT (usuario) DO UPDATE
     SET password_hash = EXCLUDED.password_hash, activo = TRUE`,
    [username, passwordHash],
  )
  console.log(`Usuario ${username} creado o actualizado correctamente.`)
} finally {
  await client.end()
}